#!/bin/bash

#remove all ?, <u>, </u>, and <br>
sed -e 's/\(?\|<u>\|<\/u>\|<br>\)//g' |

#remove \n from English lines that wrap to a new line
sed -E '/[^>]$/{N;s/\n//;}' |
sed -E '/[^>]$/{N;s/\n//;}' | 

#find all lines that start with td
grep -e "<td" | 

#delete HTML stuff at the top of the file
sed '/<td><font color/d' | 
sed '/<td width/d' | 

#delete every other line (English lines)
sed -n '0~2!p' | 

#remove all td tags
sed 's/\(<td>\|<\/td>\)//g' | 

#remove special case td tag
sed 's/<td valign="top">//g' | 

#remove another special case td tag
sed 's/<td valign="top" align="left">//g' | 

#et rid of leading and trailing spaces
sed 's/^ *//;s/ *$//;' | 

#turns ` into '
tr '\`' '\'\' | 

#turns everything into lowercase
tr '[:upper:]' '[:lower:]' | 

#replace comma, space, and dash with newline
tr '[\,\ \-]' '\n' | 

#delete all leftover empty lines
sed '/^$/d' | 

#sort list and remove duplicates
sort -u
